package com.wts.entity.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("car", "id", Car.class);
		// Composite Primary Key order: fix_id,item_id
		arp.addMapping("detail", "fix_id,item_id", Detail.class);
		arp.addMapping("fix", "id", Fix.class);
		arp.addMapping("item", "id", Item.class);
		// Composite Primary Key order: car_id,person_id
		arp.addMapping("own", "car_id,person_id", Own.class);
		arp.addMapping("person", "id", Person.class);
	}
}

