package com.wts.entity.model;

import com.wts.entity.base.BaseCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Car extends BaseCar<Car> {
	public static final Car dao = new Car().dao();
}
