package com.wts.entity.model;

import com.wts.entity.base.BaseDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Detail extends BaseDetail<Detail> {
	public static final Detail dao = new Detail().dao();
}
