package com.wts.entity.model;

import com.wts.entity.base.BaseFix;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fix extends BaseFix<Fix> {
	public static final Fix dao = new Fix().dao();
}
