package com.wts.entity.model;

import com.wts.entity.base.BaseItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Item extends BaseItem<Item> {
	public static final Item dao = new Item().dao();
}
