package com.wts.entity.model;

import com.wts.entity.base.BaseOwn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Own extends BaseOwn<Own> {
	public static final Own dao = new Own().dao();
}
